import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import Title from "@/components/ui/Title";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Facilita Planilha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${GeistMono.className} h-screen flex flex-col`}>
        <div className="flex items-center w-full justify-center pt-10">
          <a href="/">
            <Title>FACILITA PLANILHA APMG</Title>
          </a>
        </div>
        <main className="flex-1 h-full">{children}</main>
      </body>
    </html>
  );
}
